<?php

/**
 * Implements hook_menu().
 */
function linkedin_integration_menu() {
  $items = array();

  $items['linkedin-integration-testing'] = array(
    'title' => 'LinkedIn Integration Testing',
    'description' => 'This is a page for testing intergration with LinkedIn',
    'page callback' => '_linkedin_integration_testing',
  );

  return $items;
}

/**
 * Callback function for menu item linkedin-integration-testing.
 * 
 * Test function to try out the LinkedIn API using the hybridauth module.
 */
function _linkedin_integration_testing() {
  
}